---
server:
    install: '1'
    packages: [vim, git, imagemagick, build-essential, unzip]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: xenial64, hostname: bamboo.local, ip: 10.10.10.10, memory: '2048', sharedfolder: ../, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /var/www/elcodi/web
    servername: bamboo.local
mysql:
    install: '1'
    root_password: 'root'
    database: bamboo
    user: user
    password: password
    dump: ''
redis:
    install: '1'
    port: '6379'
php:
    install: '1'    
    packages: [php-cli, php-curl, php-intl, php-mcrypt, php-gd, php-mysql, php-redis, php-sqlite3, php-bcmath, php-mbstring, php-pclzip]
    pecl_packages: []
xdebug:
    install: '1'
composer:
    install: '1'

