---
- name: set permissions on socket - owner
  lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf state=present regexp='^;?listen.owner' line='listen.owner = www-data'"

- name: set permissions on socket - group
  lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf state=present regexp='^;?listen.group' line='listen.group = www-data'"

- name: set FPM user
  lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf state=present regexp='^;?user =' line='user = vagrant'"

- name: set FPM group
  lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf state=present regexp='^;?group =' line='group = vagrant'"


- name: set permissions on socket - mode
  lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf state=present regexp='^;?listen.mode' line='listen.mode = 0660'"
  notify: restart php7.0-fpm

- name: ensure timezone is set in fpm php.ini
  lineinfile: dest=/etc/php/7.0/fpm/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: enabling opcache
  lineinfile: dest=/etc/php/7.0/fpm/php.ini
              regexp=';?opcache.enable=\d'
              line='opcache.enable=1'

- name: ensure xdebug.max_nesting_level is set to 255 in fpm php.ini
  lineinfile: dest=/etc/php/7.0/fpm/php.ini
              regexp='xdebug.max_nesting_level ='
              line='xdebug.max_nesting_level = 255'


- name: enable php7.0-fpm on apache
  command: a2enconf  php7.0-fpm
