services:

    elcodi_store.store_category_tree:
        class: Elcodi\Store\ProductBundle\Services\StoreCategoryTree
        arguments:
            - "@elcodi.provider.category_tree"
            - %elcodi.core.product.load_only_categories_with_products%
            - %elcodi.core.product.cache_key%
            - "@elcodi.locale"
        calls:
            - [setCache, ["@doctrine_cache.providers.elcodi_categories"]]
            - [setEncoder, ["@elcodi.json_encoder"]]


    elcodi.manager.pack:
        class: Elcodi\Store\ProductBundle\Services\PackManager
        arguments:
            - "@elcodi.repository.purchasable_pack"
            - "@doctrine.orm.entity_manager"

    elcodi_store.twig_extension:
        class: Elcodi\Store\ProductBundle\Twig\TwigExtension
        tags:
            - { name: twig.extension }

