security:
    access_control:

        # admin
        admin_login_area:
            path: ^%bamboo_admin_pattern_prefix%/%bamboo_admin_prefix%/login.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY

        admin_password_area:
            path: ^%bamboo_admin_pattern_prefix%/%bamboo_admin_prefix%/password.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY

        admin_public_area:
            path: ^%bamboo_admin_pattern_prefix%/%bamboo_admin_prefix%/.*
            roles: ROLE_ADMIN
        
        # store
        public_area_login:
           path: ^/login$
           roles: IS_AUTHENTICATED_ANONYMOUSLY
        public_area:
            path: ^/.*
            roles: %store_access_role%


