parameters:
    permissions:
        Elcodi\Admin\AttributeBundle\Controller\AttributeController: ['attribute']
        Elcodi\Admin\BannerBundle\Controller\BannerController: ['banner']
        Elcodi\Admin\BannerBundle\Controller\BannerZoneController: ['bannerZone']
        Elcodi\Admin\CartBundle\Controller\OrderController: ['order']
        Elcodi\Admin\CartBundle\Controller\CustomerOrderController: ['order']
        Elcodi\Admin\CouponBundle\Controller\CouponController: ['coupon']
        Elcodi\Admin\CurrencyBundle\Controller\CurrencyController: ['currency']
        Elcodi\Admin\GeoBundle\Controller\CountryController: ['country']
        Elcodi\Admin\GeoBundle\Controller\LocationController: ['location']
        Elcodi\Admin\LanguageBundle\Controller\LanguageController: ['language']
        Elcodi\Admin\MediaBundle\Controller\ImageController: ['image']
        Elcodi\Admin\MetricBundle\Controller\PanelController: ['metric']
        Elcodi\Admin\MetricBundle\Controller\ReportsController: ['metric']
        Elcodi\Admin\NewsletterBundle\Controller\NewsletterSubscriptionController: ['newsletter']
        Elcodi\Admin\PageBundle\Controller\BlogPostController: ['page']
        Elcodi\Admin\PageBundle\Controller\EmailController: ['page']
        Elcodi\Admin\PageBundle\Controller\PageController: ['page']
        Elcodi\Admin\PluginBundle\Controller\PluginController: ['plugin']
        Elcodi\Admin\ProductBundle\Controller\CategoryController: ['category']
        Elcodi\Admin\ProductBundle\Controller\ManufacturerController: ['manufacturer']
        Elcodi\Admin\ProductBundle\Controller\PackController: ['pack']
        Elcodi\Admin\ProductBundle\Controller\ProductController: ['product']
        Elcodi\Admin\ProductBundle\Controller\VariantController: ['product']
        Elcodi\Admin\RuleBundle\Controller\RuleController: ['rule']
        Elcodi\Admin\SearchBundle\Controller\SearchController: ['product', 'order', 'customer', 'manufacturer']
        Elcodi\Admin\StoreBundle\Controller\StoreController: ['store']
        Elcodi\Admin\TaxBundle\Controller\TaxController: ['tax']
        Elcodi\Admin\TemplateBundle\Controller\TemplateController: ['template']
        Elcodi\Admin\UserBundle\Controller\AdminUserController: ['user']
        Elcodi\Admin\UserBundle\Controller\CustomerController: ['customer']
        Elcodi\Admin\PermissionsBundle\Controller\PermissionsController: ['permissions']
