imports:
    #
    # Bamboo security
    #
    - { resource: firewalls.yml }
    - { resource: accessControl.yml }
    - { resource: permission_rules.yml }
    - { resource: permission_rules_custom.yml, ignore_errors: true }

    #
    # Bamboo store & admin imported security
    #
    - { resource: "@ElcodiUserBundle/Resources/security/encoders.yml" }
    - { resource: "@ElcodiUserBundle/Resources/security/providers.yml" }
    - { resource: "@StoreUserBundle/Resources/security/roles.yml" }
    - { resource: "@AdminUserBundle/Resources/security/roles.yml" }
    - { resource: 'security_custom.yml', ignore_errors: true }


