store_api_login:
    path:     /store/api/login
    defaults: { _controller: StoreAPIBundle:API:login, _format: json }

store_api_logout:
    path:     /store/api/logout
    defaults: { _controller: StoreAPIBundle:API:logout, _format: json }

store_remember_password_by_email:
    path:     /store/api/remember-password-by-email
    defaults: { _controller: StoreAPIBundle:API:rememberPasswordByEmail, _format: json }

store_api_login_admin:
    path:     /store/api/login-admin
    defaults: { _controller: StoreAPIBundle:API:loginAdmin, _format: json }


store_api_get_user_data:
    path:     /store/api/get-user-data
    defaults: { _controller: StoreAPIBundle:API:getUserData, _format: json }

store_api_set_user_data:
    path:     /store/api/set-user-data
    defaults: { _controller: StoreAPIBundle:API:setUserData, _format: json }

store_api_register:
    path:     /store/api/register
    defaults: { _controller: StoreAPIBundle:API:register, _format: json }

store_api_get_orders:
    path:     /store/api/get-orders
    defaults: { _controller: StoreAPIBundle:API:getOrders, _format: json }

store_api_get_cart:
    path:     /store/api/get-cart
    defaults: { _controller: StoreAPIBundle:API:getCart, _format: json }

store_api_remove_cart_line:
    path:     /store/api/remove-cart-line
    defaults: { _controller: StoreAPIBundle:API:removeCartLine, _format: json }

store_api_create_paypal_order:
    path:     /store/api/create-paypal-order
    defaults: { _controller: StoreAPIBundle:API:createPaypalOrder, _format: json }

store_api_restore_cart_from_order:
    path:     /store/api/restore-cart-from-order
    defaults: { _controller: StoreAPIBundle:API:restoreCartFromOrder, _format: json }

store_api_update_country_language:
    path:     /store/api/update-country-language
    defaults: { _controller: StoreAPIBundle:API:updateCountryLanguage, _format: json }

store_api_update_cart_line_quantity:
    path:     /store/api/update-cart-line-quantity
    defaults: { _controller: StoreAPIBundle:API:updateCartLineQuantity, _format: json }

store_api_get_countries:
    path:     /store/api/get-countries
    defaults: { _controller: StoreAPIBundle:API:getCountries, _format: json }

store_api_get_user_address:
    path:     /store/api/get-user-addresses
    defaults: { _controller: StoreAPIBundle:API:getUserAddresses, _format: json }

store_api_add_coupon_to_cart:
    path:     /store/api/add-coupon-to-cart
    defaults: { _controller: StoreAPIBundle:API:addCouponToCart, _format: json }

store_api_remove_coupon_from_cart:
    path:     /store/api/remove-coupon-from-cart
    defaults: { _controller: StoreAPIBundle:API:removeCouponFromCart, _format: json }

store_api_create_address:
    path:     /store/api/create-address
    defaults: { _controller: StoreAPIBundle:API:createAddress, _format: json }

store_api_delete_user_address:
    path:     /store/api/delete-user-address
    defaults: { _controller: StoreAPIBundle:API:deleteUserAddress, _format: json }

store_api_set_delivery_address:
    path:     /store/api/set-delivery-address
    defaults: { _controller: StoreAPIBundle:API:setDeliveryAddressAction, _format: json }

store_api_check_email_exists:
    path:     /store/api/exists-email
    defaults: { _controller: StoreAPIBundle:API:existsCustomerEmail, _format: json }

store_api_check_vat_exists:
    path:     /store/api/exists-vat
    defaults: { _controller: StoreAPIBundle:API:existsCustomerVat, _format: json }

