services:

    #
    # Services
    #
    paymentsuite.bridge:
        class: Elcodi\Bridge\PaymentSuiteBridgeBundle\Services\PaymentBridge
        arguments:
            - "@elcodi.repository.order"
            - "@elcodi.wrapper.cart"
            - "@elcodi.store"
            - "@elcodi.converter.currency"
            - "@elcodi.name_resolver.purchasable"

    paymentsuite.order.payment_setter:
        class: Elcodi\Bridge\PaymentSuiteBridgeBundle\Services\OrderPaymentSetter
        arguments:
            - "@service_container"
            - "@paymentsuite.bridge"
            - "@elcodi.director.order"

