version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: "bamboo_db"
    ports:
      - "3307:3306"
    command:
      - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    volumes:
      - ./docker-compose/.data/db:/var/lib/mysql
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    container_name: "bamboo_web_server"
    build:
      context: .
      dockerfile: ./docker-compose/php/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/bamboo
      - ./docker-compose/php/site.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker-compose/php/myphp.ini:/usr/local/etc/php/conf.d/myphp.ini

  elastic:
    image: elasticsearch:2
    ports:
        - "9200:9200"
  
  redis:
    image: redis:3
  
  
  mailer:
    container_name: "bamboo_mailer"
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
