services:

    #
    # Services
    #
    elcodi_store.template_locator.page:
        class: Elcodi\Store\CoreBundle\Services\TemplateLocator
        arguments:
            engine: "@templating.engine.twig"
            bundles:
                - StoreOverrideBundle
                - StorePageBundle
                - StoreFallbackBundle

    elcodi_store.mailer.sender:
        class: Elcodi\Store\PageBundle\Services\Mailer
        arguments:
            - "@mailer"
            - "@twig"
            - "@elcodi.repository.page"
            - "@elcodi.store"
            - "@elcodi_store.template_locator.page"
            - "@logger"
            - "%sender_email_notification%"
