services:

    #
    # Menu builders
    #
    elcodi_admin.menu_builder.cart:
        class: Elcodi\Admin\CartBundle\Builder\MenuBuilder
        arguments:
            - "@elcodi.factory.menu_node"
            - "@service_container"
        tags:
            - { name: menu.builder, menu: admin, priority: 32 }

    elcodi_admin.menu_builder.orders_not_shipped:
        class: Elcodi\Admin\CartBundle\Builder\OrdersNotShippedBuilder
        arguments:
            - "@elcodi.factory.menu_node"
            - "@elcodi.repository.order"
            - "@service_container"
        tags:
            - { name: menu.builder, menu: admin, stage: after_cache }
