search_admin_products:
    path: /search/products
    defaults: { _controller: AdminSearchBundle:Search:searchProducts }

search_admin_component_products:
    path: /search/products/component/{query}
    defaults: { _controller: AdminSearchBundle:ProductComponent:listComponent }

search_admin_orders:
    path: /search/orders
    defaults: { _controller: AdminSearchBundle:Search:searchOrders }

search_admin_customers:
    path: /search/customers
    defaults: { _controller: AdminSearchBundle:Search:searchCustomers }