---
# application tasks to be customized and to run after the main provision

- args:
    chdir: /var/www/elcodi
  name: execute install
  shell: sh app/install.sh -f

- name: vagrant cache and log permissions
  become: yes
  shell: chown -R vagrant:vagrant /dev/shm/project/