#
# Per project config file, ignored from git, rename as config_ignored.yml
#
#
# You can add here your specific configuration. It is recomended
# to add configurations here or in config_local.yml instead of changing config.yml
# 

