#
# Per project config file
#
# You can add here your specific configuration. It is recomended
# to add configurations here instead of changing config.yml
#

fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            types: 
                products:
                    mappings:
                        sku: ~
                        name: ~
                        shortDescription: ~
                        description: ~
                    persistence:
                        driver: orm
                        model: Elcodi\Component\Product\Entity\Product
                        provider: ~
                        listener: ~
                        finder: ~
                customers:
                    mappings:
                        email: ~
                        firstName: ~
                        lastName: ~
                    persistence:
                        driver: orm
                        model: Elcodi\Component\User\Entity\Customer
                        provider: ~
                        listener: ~
                        finder: ~