services:
    elcodi.security.failure_authentication_handler:
        class: Elcodi\Store\UserBundle\Handlers\FailureAuthenticationHandler
        public: false
        arguments:
            - @router
            - @session

    # elcodi.security.success_authentication_handler:
    #     class: Elcodi\Store\UserBundle\Handlers\SuccessAuthenticationHandler
    #     public: false
    #     arguments:
    #         - '@security.http_utils'
    #         - @session

