services:


    elcodi_admin.form_type.social:
        class: Elcodi\Admin\SocialBundle\Form\Type\Admin\SocialType
        arguments:
        calls:
            - [setFactory, ["@elcodi.factory.social"] ]
            - [setEntityTranslatorFormEventListener, ["@elcodi.entity_translator_form_event_listener"] ]
        tags:
            - { name: form.type, alias: elcodi_admin_social_form_type_social }
