services:

    #
    # Menu builders
    #
    elcodi_admin.menu_builder.social:
        class: Elcodi\Admin\SocialBundle\Builder\MenuBuilder
        arguments:
            - "@elcodi.factory.menu_node"
            - "@service_container"
        tags:
            - { name: menu.builder, menu: admin, priority: 16 }
