version: '2'

services:
    db:
        build: mysql5
        ports:
            - 3307:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
          - net1

    php:
        build: php7-fpm
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        networks:
          - net1

    nginx:
        build: nginx
        ports:
            - 8080:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        networks:
            - net1

    elastic:
        image: elasticsearch:2
        ports:
            - 9200:9200
        networks:
            - net1

    redis:
        image: redis:3
        networks:
            - net1
    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: mailhog
        ports:
            - '8025:8025'
            - '1025:1025'                                                                               
        networks:
            - net1
   
networks:
    net1:
