services:

    #
    # Menu builders
    #
    elcodi.admin.menu_builder.page:
        class: Elcodi\Admin\PageBundle\Builder\MenuBuilder
        arguments:
            - "@elcodi.factory.menu_node"
            - "@service_container"
        tags:
            - { name: menu.builder, menu: admin, priority: 16 }
