doctrine_cache:
    providers:

        #
        # Categories cache
        #
        elcodi_categories:
            type: predis
            namespace: %elcodi.core.bamboo.cache_prefix%categories

        #
        # Menus cache
        #
        elcodi_menus:
            type: array
            namespace: %elcodi.core.bamboo.cache_prefix%menus

        #
        # Entity translations cache
        #
        elcodi_translations:
            type: predis
            namespace: %elcodi.core.bamboo.cache_prefix%translations

        #
        # Comments cache
        #
        elcodi_comments:
            type: predis
            namespace: %elcodi.core.bamboo.cache_prefix%comments
