snc_redis:
    clients:
        default:
            type: predis
            alias: metric
            options:
                profile: default
            dsn: redis://%redis_host%
            logging: false
