services:

    elcodi_store.store_search:
        class: Elcodi\Store\SearchBundle\Services\StoreSearchService
        arguments:
            - '@service_container'
            - '%elcodi.core.bamboo.cache_prefix%'
            - '%item_for_page%'
            - '@elcodi.converter.currency'
            - '%category_default_connector%'
            - '%product_partial_search%'
            - '%category_partial_search%'