services:

    #
    # Services
    #
    elcodi_store.template_locator.core:
        class: Elcodi\Store\CoreBundle\Services\TemplateLocator
        arguments:
            engine: "@templating.engine.twig"
            bundles:
                - StoreOverrideBundle
                - "@elcodi.store_template_bundle"
                - StoreFallbackBundle
    
    elcodi_store.manager.datetime:
        class: Elcodi\Store\CoreBundle\Services\DateTimeManager

