services:

    #
    # Menu builders
    #
    elcodi_admin.menu_builder.plugin_list:
        class: Elcodi\Admin\PluginBundle\Builder\MenuBuilder
        arguments:
            - "@elcodi.factory.menu_node"
            - "@service_container"
        tags:
            - { name: menu.builder, menu: admin, priority: 32 }
